[package]
name = "algo_challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = {version = "0.15", features = [ "native-tls", "rustls"] }
tungstenite = "0.13"
